#version 430

uniform layout(r8) readonly image2D readTexture;
uniform layout(r8) writeonly image2D writeTexture;

layout(local_size_x = 16, local_size_y = 16) in;

void main() {

    // upsample by 4x4 kernels
    ivec2 ID = ivec2(gl_GlobalInvocationID.xy);
    // every 4x4 block of pixels fetches in only one pixel from the read texture
    float result = imageLoad(readTexture, ID / 4).r;
    imageStore(writeTexture, ID, vec4(vec3(result), 1.0));
}